# Import automatique des contrôleurs
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Routes personnalisées (au cas où)
app_home:
    path: /
    controller: App\Controller\HomeController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: [GET, POST]

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
    methods: [GET]

app_signup:
    path: /signup
    controller: App\Controller\SignupController::signup
    methods: [GET, POST]
dashboard_admin:
    path: /admin/dashboard
    controller: App\Controller\EvenementController::dashboard
    methods: GET