# config/packages/web_profiler.yaml

when@dev:
    web_profiler:
        toolbar: false               # ← désactive la barre en haut de page
        intercept_redirects: false   # ← empêche d'intercepter les redirections

when@test:
    framework:
        profiler: { collect: false }